version: '3.0'

services:
  #Runner APP
  webapi:
    container_name: ramosisw_todoapi_webapi
    image: ramosisw/todoapi:rpi_${WEBAPP_VERSION}
    build:
      context: .
      dockerfile: ./rpi.dockerfile
      args:
        WEBAPP_VERSION: ${WEBAPP_VERSION}
        URL_HTTP_INT_PORT: ${URL_HTTP_INT_PORT}
    ports:
      - ${URL_HTTP_EXT_PORT}:${URL_HTTP_INT_PORT}
    volumes:
      - app:/app
    depends_on:
      - db
      
  #Database for APP
  db:
    image: mysql:5.7
    container_name: ramosisw_todoapi_db
    #hostname: todoapi-mysql
    environment:
      #MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_EXT_PORT}:${MYSQL_INT_PORT}
    restart: always

volumes:
  app: